export const ZkbSearchCriteriaType = {
  Kills: 'kills',
  Losses: 'losses',
  Ganked: 'ganked',
  Solo: 'solo',
  Finalblow: 'finalblow-only',
  Alliance: 'alliance',
  Corporation: 'corporation',
  Character: 'character',
  Highsec: 'highsec',
  Lowsec: 'lowsec',
  Nullsec: 'nullsec',
  WSpace: 'w-space',
  Abyssal: 'abyssal',
  Group: 'group',
  Ship: 'ship',
  Region: 'region',
  Constellation: 'constellation',
  System: 'system',
  IskValue: 'iskValue'
}
